### ISSUE TITLE
Create chocolate package to install Windows version

### ISSUE THREAD

**Issue by jawn** [GreatWebGuy/MobTime#30] opened 2021-01-13 09:54 UTC
Create a chocolatey package for MobTime. This provides easy installation and updates.

http://chocolatey.org

**Comment by jawn** [comment] 2021-01-13 09:55
I am willing to pair/mob on this, ping me if interested. I have no experience in creating such a package, however the [docs are out there](https://docs.chocolatey.org/en-us/create/).

**Comment by jlcrow** [comment] 2021-03-17 22:16
This is a duplicate of #29

**Closed as completed** 2021-03-17 22:15 UTC
